{% set version = "1.0.1" %}

package:
  name: requests-futures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-futures/requests-futures-{{ version }}.tar.gz
  sha256: f55a4ef80070e2858e7d1e73123d2bfaeaf25b93fd34384d8ddf148e2b676373

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  host:
    - python
    - pip
    - setuptools >=38.6.1
  run:
    - python
    - requests >=1.2.0

test:
  imports:
    - requests_futures
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/ross/requests-futures
  license: Apache-2.0
  license_file: LICENSE
  summary: Asynchronous Python HTTP for Humans

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
