{% set version = "0.9.7" %}


package:
  name: requests-futures
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests-futures/requests-futures-{{ version }}.tar.gz
  sha256: a9ca2c3480b6fac29ec5de59c146742e2ab2b60f8c68581766094edb52ea7bad

build:
  number: 1002
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - requests >=1.2.0

test:
  imports:
    - requests_futures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ross/requests-futures
  summary: Asynchronous Python HTTP for Humans
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
