{% set name = "requests-futures" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/requests-futures-{{ version }}.tar.gz
  sha256: f55a4ef80070e2858e7d1e73123d2bfaeaf25b93fd34384d8ddf148e2b676373

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=38.6.1
    - pip
  run:
    - python >=3.6
    - requests >=1.2.0

test:
  imports:
    - requests_futures
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ross/requests-futures
  summary: Asynchronous Python HTTP for Humans.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
